changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: "✨ New Features"
      labels:
        - feature
        - enhancement
    - title: "🐛 Bug Fixes"
      labels:
        - bug
        - fix
    - title: "⚡ Performance"
      labels:
        - performance
    - title: "🔧 Other Changes"
      labels:
        - "*"
