name = "viewerleaf-collab"
main = "src/index.ts"
compatibility_date = "2026-03-15"

[[durable_objects.bindings]]
name = "DOCUMENT_ROOM"
class_name = "DocumentRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["DocumentRoom"]

[[d1_databases]]
binding = "DB"
database_name = "viewerleaf"
database_id = "a3b3c92f-612e-4d38-930c-943da83939b0"

[[kv_namespaces]]
binding = "BLOBS"
id = "71d6d53be3154bddae01df4beb7fb067"

[vars]
ALLOW_INSECURE_AUTH = "true"

